jobs:
  build:
    docker:
      - image: circleci/openjdk
      steps:
        - checkout 
        - run:
          name: "Ejecucion" 
          command: |
            echo "A first hello"
            ls --all
            pwd 
            echo "Finished"              
            scp -o StrictHostKeyChecking=no ./index.html ubuntu@ec2-54-160-54-237.compute-1.amazonaws.com:/mnt/sharedfolder/
 
                   
            


            

