 version: 2
 jobs:
   build:
     docker:
       - image: circleci/openjdk
     steps:
       - checkout
       - run:
          name: "Ejecucion" 
          command: |
            echo "A first hello"
            ls 
            pwd -all
            echo "Finished"
            

